vim.cmd('source ' .. '~/.config/nvim/origin-vimscripts/memo.vim')
vim.cmd('source ' .. '~/.config/nvim/origin-vimscripts/smooth_scroll.vim')
vim.cmd('source ' .. '~/.config/nvim/origin-vimscripts/start_up.vim')
vim.cmd('source ' .. '~/.config/nvim/origin-vimscripts/todo.vim')
vim.cmd('source ' .. '~/.config/nvim/origin-vimscripts/yank_path.vim')
